package com.example.suitcase.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDarkBlue = Color(0xFF223E6D)
val primaryLightBlue = Color(0xFF367BE2)
val secondaryDarkBlue = Color(0xFF92A5C6)
val secondaryLightBlue = Color(0xFFBBC7DB)




val light_primary = Color(0xFF5141E6)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFE3DFFF)
val light_onPrimaryContainer = Color(0xFF120068)
val light_secondary = Color(0xFF5E5C71)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE3E0F9)
val light_onSecondaryContainer = Color(0xFF1B1A2C)
val light_tertiary = Color(0xFF7A5367)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFD8E9)
val light_onTertiaryContainer = Color(0xFF2F1123)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1C1B1F)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1C1B1F)
val light_surfaceVariant = Color(0xFFE5E1EC)
val light_onSurfaceVariant = Color(0xFF47464F)
val light_outline = Color(0xFF787680)
val light_inverseOnSurface = Color(0xFFF3EFF4)
val light_inverseSurface = Color(0xFF313034)
val light_inversePrimary = Color(0xFFC4C0FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF5141E6)
val light_outlineVariant = Color(0xFFC8C5D0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFC4C0FF)
val dark_onPrimary = Color(0xFF2200A3)
val dark_primaryContainer = Color(0xFF371ECF)
val dark_onPrimaryContainer = Color(0xFFE3DFFF)
val dark_secondary = Color(0xFFC7C4DC)
val dark_onSecondary = Color(0xFF302E42)
val dark_secondaryContainer = Color(0xFF464559)
val dark_onSecondaryContainer = Color(0xFFE3E0F9)
val dark_tertiary = Color(0xFFEBB9D0)
val dark_onTertiary = Color(0xFF472638)
val dark_tertiaryContainer = Color(0xFF603B4F)
val dark_onTertiaryContainer = Color(0xFFFFD8E9)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1C1B1F)
val dark_onBackground = Color(0xFFE5E1E6)
val dark_surface = Color(0xFF1C1B1F)
val dark_onSurface = Color(0xFFE5E1E6)
val dark_surfaceVariant = Color(0xFF47464F)
val dark_onSurfaceVariant = Color(0xFFC8C5D0)
val dark_outline = Color(0xFF928F99)
val dark_inverseOnSurface = Color(0xFF1C1B1F)
val dark_inverseSurface = Color(0xFFE5E1E6)
val dark_inversePrimary = Color(0xFF5141E6)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFC4C0FF)
val dark_outlineVariant = Color(0xFF47464F)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4735DD)
